#!/usr/bin/env python3
"""
gen_spawn_types.py — scan the ModernUO UOContent source and emit
spawn_types.json: the categorized list of concrete, spawnable Mobile type
names the map editor's "what spawns here" dropdown reads.

Approach (no runtime/game build needed):
  1. Walk every .cs under Projects/UOContent, recording `class X : Base`
     declarations (name -> immediate base, + source file path, + abstract?).
  2. Resolve inheritance transitively: a class is spawnable if it (eventually)
     derives from BaseCreature or BaseVendor and is NOT abstract.
  3. Categorize by source-folder + base:
       vendor  -> derives from BaseVendor
       npc     -> BaseCreature under Mobiles/Townfolk|Healers|Hireables
       animal  -> BaseCreature under Mobiles/Animals
       monster -> every other concrete BaseCreature (Monsters/Special/etc.)
The game's AssemblyHandler.FindTypeByName is the real validator at generation
time, so an approximate-but-good list here is fine — the dropdown is a
convenience, not the source of truth.

Run:  python gen_spawn_types.py
Writes spawn_types.json next to this script (and mirrors to ~/uo-map).
"""
import json, os, re, shutil

UOCONTENT = os.path.expanduser("~/uo-modernuo/ModernUO/Projects/UOContent")
OUT_LOCAL = os.path.join(os.path.dirname(os.path.abspath(__file__)), "spawn_types.json")
OUT_RUN   = os.path.expanduser("~/uo-map/spawn_types.json")

# `public [sealed|abstract] [partial] class Name : Base, IFoo, ...`
CLASS_RE = re.compile(
    r'\bclass\s+([A-Za-z_]\w*)\s*:\s*([A-Za-z_]\w*)', re.M)
ABSTRACT_RE = re.compile(r'\babstract\s+(partial\s+)?class\b')

# Roots that mean "this is a spawnable mobile".
CREATURE_ROOTS = {"BaseCreature"}
VENDOR_ROOTS   = {"BaseVendor"}


def scan():
    # name -> {"base":..., "path":..., "abstract":bool}
    decls = {}
    for root, _dirs, files in os.walk(UOCONTENT):
        # skip build output
        if os.sep + "obj" in root or os.sep + "bin" in root:
            continue
        for fn in files:
            if not fn.endswith(".cs"):
                continue
            path = os.path.join(root, fn)
            try:
                text = open(path, encoding="utf-8-sig").read()
            except Exception:
                continue
            for m in CLASS_RE.finditer(text):
                name, base = m.group(1), m.group(2)
                # is this specific class declaration abstract? check the
                # ~40 chars before the match for the abstract keyword.
                head = text[max(0, m.start() - 40):m.start()]
                is_abstract = bool(ABSTRACT_RE.search(head + " class"))
                # first declaration wins (partial classes repeat)
                if name not in decls:
                    decls[name] = {"base": base, "path": path,
                                   "abstract": is_abstract}
    return decls


def root_of(name, decls, _seen=None):
    """Walk up the base chain; return the topmost known base name."""
    seen = _seen or set()
    cur = name
    while cur in decls and cur not in seen:
        seen.add(cur)
        cur = decls[cur]["base"]
    return cur  # the first base not itself declared (e.g. BaseCreature)


def derives_from(name, roots, decls):
    seen = set()
    cur = name
    while cur and cur not in seen:
        seen.add(cur)
        if cur in roots:
            return True
        nxt = decls.get(cur, {}).get("base")
        if nxt is None:
            return False
        cur = nxt
    return False


def categorize(name, info, decls):
    path = info["path"].replace("\\", "/")
    is_vendor = derives_from(name, VENDOR_ROOTS, decls)
    is_creature = derives_from(name, CREATURE_ROOTS, decls)
    if not (is_vendor or is_creature):
        return None
    if is_vendor:
        return "vendor"
    # creature: split by folder
    if "/Mobiles/Animals/" in path:
        return "animal"
    if ("/Mobiles/Townfolk/" in path or "/Mobiles/Healers/" in path
            or "/Mobiles/Hireables/" in path):
        return "npc"
    return "monster"


def main():
    decls = scan()
    cats = {"monster": [], "animal": [], "npc": [], "vendor": []}
    for name, info in decls.items():
        if info["abstract"]:
            continue
        # skip our own PlayerBot family — bots are placed via bot kinds
        if name.startswith("PlayerBot"):
            continue
        # skip abstract-ish base classes that aren't marked `abstract`
        # but are never spawned directly (BaseHire, BaseEscortable, ...)
        if name.startswith("Base"):
            continue
        cat = categorize(name, info, decls)
        if cat:
            cats[cat].append(name)
    for k in cats:
        cats[k] = sorted(set(cats[k]))
    out = {
        "_comment": "Spawnable Mobile type names for the map editor dropdown. "
                    "Generated by gen_spawn_types.py from UOContent source. "
                    "AssemblyHandler.FindTypeByName validates at generation time.",
        "categories": cats,
        "counts": {k: len(v) for k, v in cats.items()},
    }
    body = json.dumps(out, indent=2)
    open(OUT_LOCAL, "w").write(body)
    try:
        if os.path.isdir(os.path.dirname(OUT_RUN)):
            shutil.copy(OUT_LOCAL, OUT_RUN)
    except Exception as ex:
        print("mirror to ~/uo-map failed (ok if not deployed):", ex)
    print("wrote", OUT_LOCAL)
    print("counts:", out["counts"])


if __name__ == "__main__":
    main()
